Omit timestamp from PE executable
greenbone/openvas-smb pull request #40
Opened 2021-06-12 03:44 UTC by bmwiedemann

Omit timestamp from PE executable
to make binaries reproducible.
See https://reproducible-builds.org/ for why this is good.

This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).

2021-06-13 11:32 UTC, bjoernricks commented
Thanks for your contribution! Would be nice if you could do a quick changelog entry

2021-06-14 07:29 UTC, cfi-gb commented
Note that this code might be also a candidate for complete removal, ref: #24

2021-06-14 07:44 UTC, bmwiedemann commented
Added a changelog entry. Removal would also be fine for reproducible builds.

2021-06-14 07:53 UTC, y0urself requested changes

2021-06-14 07:53 UTC, y0urself commented on CHANGELOG.md
> +- Build winexesvc without timestamps to make binaries reproducible
```suggestion
- Build winexesvc without timestamps to make binaries reproducible [#40](https://github.com/greenbone/openvas-smb/pull/40)
```

2021-06-14 11:56 UTC, bjoernricks approved these changes

2021-06-15 07:28 UTC, merged